# File: src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://helios:5432/lct_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: NON_NULL

  main:
    banner-mode: off

  application:
    name: delivery-unit-backend

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.onboarding: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG

cps:
  jira:
    base-url: http://helios:8080
  webhook:
    disable-auth: true
    secret: changeme
  fields:
    gov-summary: "Governance Summary"
    gov-status: "Governance Status"
    notes: "Control Pack Notes"
  default-pack:
    id: DG-CAP-001
    version: 1.0.0
  forms:
    base-url: http://mars:5173/forms

opa:
  base-url: http://mars:8181
  path: /v1/data/change_arb/result
  connect-timeout-ms: 5000
  read-timeout-ms: 5000
  # auth-header: "Bearer xxx"   # optional

app:
  external-apis:
    gitlab:
      token: ${GITLAB_API_TOKEN:}
    confluence:
      username: ${CONFLUENCE_USERNAME:}
      token: ${CONFLUENCE_API_TOKEN:}

autoprofile:
  enabled: true
  registryPath: classpath:profile-fields.registry.yaml
  scopeType: application

features:
  reuseSuggestions: true

# Document URL validation configuration
document-validation:
  allowed-domains:
    # Official GitLab domains
    gitlab:
      - "gitlab.com"
      - "gitlab.io"
    # Official Confluence/Atlassian domains  
    confluence:
      - "atlassian.net"
      - "atlassian.com"
    # Corporate self-hosted domains (configurable per environment)
    corporate:
      - "butterflycluster.com"
      - "corp.company.org" 
      - "internal.enterprise.net"
  
  # Domains that are always rejected
  blocked-domains:
    - "example.com"
    - "example.org" 
    - "example.net"
    - "test.com"
    - "localhost"
    - "127.0.0.1"
    - "0.0.0.0"
  
  # Patterns that indicate fake/test domains
  blocked-patterns:
    - "example"
    - "test" 
    - "fake"
    - "mock"
    - "dummy"
    - "placeholder"
    - "demo"
  
  # Response validation settings
  response-validation:
    # Minimum content requirements for valid responses
    min-title-length: 3
    min-content-size: 100
    # Required HTTP status codes that indicate valid content
    valid-status-codes: [200, 302]
    # Timeout for validation requests (ms)
    validation-timeout: 30000


audit:
  enabled: true
  producer-id: po-service
  sink:
    url: http://localhost:8081/audit/events
  api-key: dev-key

