# File: src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://helios:5432/lct_data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: NON_NULL

  main:
    banner-mode: off

  application:
    name: delivery-unit-backend

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.onboarding: DEBUG
    org.springframework.jdbc.core: WARN
    org.springframework.jdbc.datasource: WARN

cps:
  jira:
    base-url: http://helios:8080
  webhook:
    disable-auth: true
    secret: changeme
  fields:
    gov-summary: "Governance Summary"
    gov-status: "Governance Status"
    notes: "Control Pack Notes"
  default-pack:
    id: DG-CAP-001
    version: 1.0.0
  forms:
    base-url: http://mars:5173/forms

opa:
  base-url: http://mars:8181
  path: /v1/data/change_arb/result
  connect-timeout-ms: 5000
  read-timeout-ms: 5000
  # auth-header: "Bearer xxx"   # optional

app:
  external-apis:
    gitlab:
      token: ${GITLAB_API_TOKEN:}
    confluence:
      username: ${CONFLUENCE_USERNAME:}
      token: ${CONFLUENCE_API_TOKEN:}

autoprofile:
  enabled: true
  registryPath: classpath:profile-fields.registry.yaml
  scopeType: application

features:
  reuseSuggestions: true

# Document URL validation configuration
document-validation:
  # Platform-specific allowed domains for strict validation
  platform-domains:
    gitlab:
      - "gitlab.com"
      - "gitlab.io"
      - "eros.butterflycluster.com"  # Corporate GitLab instance
    confluence:
      - "atlassian.net"
      - "atlassian.com"
      - "confluence.butterflycluster.com"  # Corporate Confluence (if exists)
    # Future platforms can be added here
    # sharepoint:
    #   - "sharepoint.com"
    #   - "office.com"
  
  # Strict mode: only allow configured platform domains
  strict-mode: true
  
  # Response validation settings
  response-validation:
    # Minimum content requirements for valid responses
    min-title-length: 3
    min-content-size: 100
    # Required HTTP status codes that indicate valid content
    valid-status-codes: [200, 302]
    # Timeout for validation requests (ms)
    validation-timeout: 30000


audit:
  enabled: true
  producer-id: po-service
  sink:
    url: http://localhost:8081/audit/events
  api-key: dev-key
  # For local development - log audit events when sink is unavailable
  log-on-failure: true

