CREATE TABLE risk_story (
    risk_id TEXT PRIMARY KEY,
    app_id TEXT NOT NULL,
    field_key TEXT NOT NULL,
    profile_id TEXT,
    profile_field_id TEXT,
    track_id TEXT,
    title TEXT,
    hypothesis TEXT,
    condition TEXT,
    consequence TEXT,
    control_refs TEXT,
    attributes JSONB DEFAULT '{}',
    severity TEXT DEFAULT 'medium',
    status TEXT DEFAULT 'open',
    closure_reason TEXT,
    raised_by TEXT NOT NULL,
    owner TEXT,
    opened_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_app_id FOREIGN KEY (app_id) REFERENCES application(app_id),
    CONSTRAINT fk_profile_id FOREIGN KEY (profile_id) REFERENCES profile(profile_id),
    CONSTRAINT fk_profile_field_id FOREIGN KEY (profile_field_id) REFERENCES profile_field(id),
    CONSTRAINT fk_track_id FOREIGN KEY (track_id) REFERENCES track(track_id)
);